" encoding / file encoding
set enc=utf-8
set fenc=utf-8

" do not emulate old vi
set nocompatible

" indents: use tabs, width 2 spaces, maintain indent on new line
set tabstop=2
set softtabstop=0
set noexpandtab
set shiftwidth=2
set autoindent
set smartindent

" display line numbers
set number

" highlight matching braces
set showmatch

syntax on
